LIB_INSTALL_DIR ?= $(shell component-tool --repo=libtins --type=$(BUILD_TYPE) localpath libtins-dev)

all: build

build:
	(mkdir build; cd build; cmake ../ -DLIBTINS_ENABLE_CXX11=1 -DLIBTINS_ENABLE_ACK_TRACKER=0 -DLIBTINS_ENABLE_WPA2=0 -DLIBTINS_ENABLE_DOT11=1; make)

install: 
	(cd build; sudo make install DESTDIR=$(LIB_INSTALL_DIR))

checkin:
	$(Q)component-tool checkin -v --repo=libtins --type=$(BUILD_TYPE) libtins-dev


clean:
	@rm build -rf

.PHONY: build 